### ISSUE TITLE
很奇怪 项目明明已经编译通过并且成功运行起来了的 但是突然就莫名其妙的编译通不过了 错误基本都是少属性 比如某个类的viewModel没有 然后点进这个类看  也确实没有这个属性 真奇怪  之前编译通过是怎么做到的...

### ISSUE THREAD

**Issue by jhchenchong** [Josin22/Yuncai#5]

**Comment by aq12345** [comment]
刚刚测试了下，Xcode 8.3.1能成功编译运行。

**Comment by Josin22** [comment]
试试这个[Linker command failed with exit code](http://blog.csdn.net/dingqk/article/details/76531760)

**Comment by LeeJunhui** [comment]
@Josin22 看了你发的这个链接，感觉并不适用啊，我的mac上现在只有一个Xcode9.0

**Comment by Josin22** [comment]
我电脑xcode9 和8都运行ok

**Comment by LeeJunhui** [comment]
你的电脑上是同时有2个Xcode?
发自网易邮箱大师
在2017年09月30日 17:42，乔同X 写道： 我电脑xcode9 和8都运行ok

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Josin22/Yuncai","title":"Josin22/Yuncai","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Josin22/Yuncai"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Josin22 in #5: 我电脑xcode9 和8都运行ok"}],"action":{"name":"View Issue","url":"https://github.com/Josin22/Yuncai/issues/5#issuecomment-333297191"}}}

**Comment by Josin22** [comment]
对的

**Comment by hongdong** [comment]
不是多个版本的问题，是项目里面有好多重名的(deprecated)的文件，可能link错了。
